sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
before_script:
  #- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && \
  #  chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - docker build -t androidotai/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true androidotai/react-test npm test

# deploy:
#   provider: openshift
#   user: "YOU USER NAME"
#   password: "YOUR PASSWORD" # can be encrypted
#   domain: "YOUR OPENSHIFT DOMAIN"

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master